---
title: "Lab_data_w/o_no-standstill_starts"
author: "Kayla Pehl"
date: "10/1/2020"
output: html_document
---

# This dataset does NOT include trials where the lizard did not start from a standstill

```{r}
#Importing data and required packages

lab.data <- read.csv("~/College of Charleston/Thesis/Videos Digitized/Thesis_videos_digitized_condensed_final_10.08.20_removed_non-standstill_starts+NA.csv")
library(ggplot2)
library(rcompanion)
library(lme4)
library(sjstats)
```


# Creating histograms to see distribution of data

```{r}
#Side max acceleration max per substrate 
ggplot(data = lab.data, aes(side_amax))  + 
  geom_histogram(fill="orange", bins = 20, binwidth = 10) +
  facet_wrap(~substrate_type) +
  labs(title = "Side max acceleration per substrate")

#Side max acceleration max per sex
ggplot(data = lab.data, aes(side_amax))  + 
  geom_histogram(fill="orange", bins = 20, binwidth = 5) +
  facet_wrap(~sex) +
  labs(title = "Side max acceleration per sex")
```

```{r}
#Top max acceleration max per substrate 
ggplot(data = lab.data, aes(top_amax))  + 
  geom_histogram(fill="purple", bins = 30, binwidth = 10) +
  facet_wrap(~substrate_type) +
  labs(title = "Top max acceleration per substrate")

#Top max acceleration max per sex
ggplot(data = lab.data, aes(top_amax))  + 
  geom_histogram(fill="purple", bins = 30, binwidth = 5) +
  facet_wrap(~sex) +
  labs(title = "Top max acceleration per sex")
```

```{r}
#Bipedalism percentage per sex Histogram
ggplot(data = lab.data, aes(as.numeric(bipedal_percent)))  + 
  geom_histogram(fill="dark green", bins = 20, binwidth = 10) +
  facet_wrap(~sex)

#Bipedalism percentage per substrate Histogram
ggplot(data = lab.data, aes(as.numeric(bipedal_percent)))  + 
  geom_histogram(fill="dark green", bins = 20, binwidth = 10) +
  facet_wrap(~substrate_type)
```


```{r}
#Boxplots of Bipedalism on acceleration 

ggplot(data = lab.data, aes(x=bipedal_quad_side, y=side_amax)) +
  geom_boxplot() +
    labs(title = "Bipedalism effect on max acceleration (side)")

ggplot(data = lab.data, aes(x=bipedal_quad_top, y=top_amax)) +
  geom_boxplot() +
    labs(title = "Bipedalism effect on max acceleration (top)")
```

```{r}
#Boxplots of Bipedalism on velocity

ggplot(data = lab.data, aes(x=bipedal_quad_side, y=side_vmax)) +
  geom_boxplot() +
    labs(title = "Bipedalism effect on max velocity (side)")

ggplot(data = lab.data, aes(x=bipedal_quad_top, y=top_vmax)) +
  geom_boxplot() +
    labs(title = "Bipedalism effect on max velocity (top)")
```

```{r}
#Histograms of pmax, posmax and tmax
ggplot(data = lab.data, aes(side_pmax)) +
  geom_histogram(fill = "dark blue") +
    labs(title = "Side Pmax")

ggplot(data = lab.data, aes(side_posmax)) +
  geom_histogram(fill = "dark blue") +
    labs(title = "Side Posmax")

ggplot(data = lab.data, aes(side_tmax)) +
  geom_histogram(fill = "dark blue") +
    labs(title = "Side Tmax")

ggplot(data = lab.data, aes(top_pmax)) +
  geom_histogram(fill = "medium blue") +
    labs(title = "Top Pmax")

ggplot(data = lab.data, aes(top_posmax)) +
  geom_histogram(fill = "medium blue") +
    labs(title = "Top Posmax")

ggplot(data = lab.data, aes(top_tmax)) +
  geom_histogram(fill = "medium blue") +
    labs(title = "Top Tmax")
```



```{r}
table(lab.data$bipedal_quad_side)
table(lab.data$bipedal_quad_top)
```


```{r}
#Summary of data
summary(lab.data)
```

```{r}
summary(lm(side_amax~sex, data = lab.data))
```


# Checking for normality

```{r}
#Checking for normality of data: max accelerations and velocities

#histograms
ggplot(data = lab.data, aes(side_amax))  + 
  geom_histogram(bins = 11, col = ("grey"))

ggplot(data = lab.data, aes(top_amax))  + 
  geom_histogram(bins = 11, col = ("grey"))

ggplot(data = lab.data, aes(side_vmax))  + 
  geom_histogram(bins = 13, col = ("grey"))

ggplot(data = lab.data, aes(top_vmax))  + 
  geom_histogram(bins = 11, col = ("grey"))

#Shapiro-Wilks normality test (p-value <0.05 is normal)
shapiro.test(lab.data$side_amax)
shapiro.test((lab.data$top_amax))
shapiro.test((lab.data$side_vmax))
shapiro.test(lab.data$top_vmax)

#side_amax: normal
#top_amax: normal
#side_vmax: not normal
#top_vmax: not normal
```

```{r}
#Checking for normality of data: time and position

#historgrams
ggplot(data = lab.data, aes(side_tmax))  + 
  geom_histogram(bins = 11, col = ("grey"))

ggplot(data = lab.data, aes(top_tmax))  + 
  geom_histogram(bins = 11, col = ("grey"))

ggplot(data = lab.data, aes(side_posmax))  + 
  geom_histogram(bins = 13, col = ("grey"))

ggplot(data = lab.data, aes(top_posmax))  + 
  geom_histogram(bins = 11, col = ("grey"))

#Shapiro-Wilks normality test (p-value <0.05 is normal)
shapiro.test(lab.data$side_tmax)
shapiro.test((lab.data$top_tmax))
shapiro.test((lab.data$side_posmax))
shapiro.test(lab.data$top_posmax)

#side_tmax: normal
#top_tmax: normal
#side_posmax: not normal
#top_posmax: normal
```


# Looking at diagnostics data

```{r}
#Top camera max acceleration vs. bipedalism in side

top.amax.biped <- lm(top_amax ~ bipedal_top, data = lab.data)
res.top.amax.biped <- resid(top.amax.biped)
plot(fitted(top.amax.biped), res.top.amax.biped)
abline(0,0)

qqnorm(res.top.amax.biped)
qqline(res.top.amax.biped,
       col = 'red')
plot(density(res.top.amax.biped))

plot(top.amax.biped)
```

```{r}
#Side camera max acceleration vs. bipedalism in side
side.amax.biped <- lm(side_amax ~ bipedal_side, data = lab.data)
res.side.amax.biped <- resid(side.amax.biped)
plot(fitted(side.amax.biped), res.side.amax.biped)

qqnorm(res.side.amax.biped)
qqline(res.side.amax.biped,
       col = 'red')
plot(density(res.side.amax.biped))

plot(side.amax.biped)
```

```{r}
#Side camera max velocity vs. bipedalism in side
side.vmax.biped <- lm(side_vmax ~ bipedal_side, data = lab.data)
res.side.vmax.biped <- resid(side.vmax.biped)
plot(fitted(side.vmax.biped), res.side.vmax.biped)

qqnorm(res.side.vmax.biped)
qqline(res.side.vmax.biped,
       col = 'red')
plot(density(res.side.vmax.biped))

plot(side.vmax.biped)
```

```{r}
#Log transform side camera max velocity vs. bipedalism in side

log_side_vmax <- log(lab.data$side_vmax)
log.side.vmax.biped <- lm(log_side_vmax ~ bipedal_side, data = lab.data)
res.log.side.vmax.biped <- resid(log.side.vmax.biped)
plot(fitted(log.side.vmax.biped), res.log.side.vmax.biped)

qqnorm(res.log.side.vmax.biped)
qqline(res.log.side.vmax.biped,
       col = 'red')
plot(density(res.log.side.vmax.biped))

plot(log.side.vmax.biped)

ggplot(data = lab.data, aes(log_side_vmax))  + 
  geom_histogram(bins = 13, col = ("grey"))    #skewed left

plot(lm(side_vmax ~ bipedal_side, data = lab.data))  #Side vmax vs. bipedalism

#Q-Q plots of regular and log-transformed side vmax data look basically the same to me. I'm not sure if log-transforming did a lot for the data.
```

```{r}
#Comparing side vmax data from original with log-transformed

#histograms
plotNormalHistogram(lab.data$side_vmax)  #appears pretty symmetrical 
plotNormalHistogram(log_side_vmax)  #skew left

#Shapiro-Wilks test for normality
shapiro.test(lab.data$side_vmax)  #not normal
shapiro.test(log_side_vmax)  #normal
```


```{r}
#Log transform top camera max velocity vs. bipedalism in top

log_top_vmax <- log(lab.data$top_vmax)
log.top.vmax.biped <- lm(log_top_vmax ~ bipedal_top, data = lab.data)
res.log.top.vmax.biped <- resid(log.top.vmax.biped)
plot(fitted(log.top.vmax.biped), res.log.top.vmax.biped)

qqnorm(res.log.top.vmax.biped)
qqline(res.log.top.vmax.biped,
       col = 'red')
plot(density(res.log.top.vmax.biped))

plot(log.top.vmax.biped)

plot(lm(top_vmax ~ bipedal_top, data = lab.data))  #not transformed
```

```{r}
#Comparing top vmax data from original with log-transformed

#histograms
plotNormalHistogram(lab.data$top_vmax)  #appears pretty symmetrical 
plotNormalHistogram(log_top_vmax)  #skew left

#Shapiro-Wilks test for normality
shapiro.test(lab.data$top_vmax)  #not normal
shapiro.test(log_top_vmax)  #normal
```


```{r}
#Trying to determine if bipedal_top needs to be transformed

#Non-transformed
plotNormalHistogram(as.numeric(lab.data$bipedal_top), main = "Non-transformed")  #skewed left

#Squared
dat <- as.numeric(lab.data$bipedal_top)
newdat <- dat^2
plotNormalHistogram(newdat, main = "Bipedal_top Squared")  #even more skewed left than regular bipedal_top

#Exponential
newdat2 <- exp(dat)
plotNormalHistogram(newdat2, main = "Exponential")  #even more un-normal than non-transformed

#Reciprocal 
newdat3 <- 1/dat
plotNormalHistogram(newdat3, main = "Reciprocal")  #made bipedal_top skewed right and it's even worse than non-transformed

#Bipedal_top looks best non-transformed
```











# Linear Models with Interaction Effects

```{r}
#Velocity

anova(lm(top_vmax ~ sex*bipedal_top*substrate_type*ID, data=lab.data))
#sex, bipedal_top & substrate type are all significant by themselves

anova(lm(side_vmax ~ sex*bipedal_side*substrate_type*ID, data = lab.data))
#sex and bipedalism were very significant by themselves
#ID was also significant by itself
```

```{r}
#Acceleration

anova(lm(top_amax ~ sex*bipedal_top*substrate_type*ID, data = lab.data))
#nothing is significant

anova(lm(side_amax ~ sex*bipedal_side*substrate_type*ID, data = lab.data))
#nothing is significant
```

















# Bipedal Percentage

```{r}
#Bipedal Percentage Plots

#Creating new data frame without N/A's
lab.data_omit <- lab.data[!is.na(lab.data$bipedal_percent), ]

#Histogram of bipedal percent without N/A's
ggplot(data = lab.data_omit, aes(as.numeric(bipedal_percent))) +
  geom_histogram(col = "white") + 
  labs(title = "Histogram of Bipedal Percent (without N/As)")

#Histogram of bipedal percent without N/A's separated into substrate type
ggplot(data = lab.data_omit, aes(as.numeric(bipedal_percent))) +
  geom_histogram(bins = 20, binwidth = 8) +
  facet_wrap(~substrate_type)

#Boxplot of bipedal percent without N/A's separated by substrate type
ggplot(data = lab.data_omit, aes(substrate_type, as.numeric(bipedal_percent))) +
  geom_boxplot() + 
  labs(title = "Boxplot of Bipedal Percent (without N/As) by Substrate Type")

#Boxplot of bipedal percent without N/A's separated by sex
ggplot(data = lab.data_omit, aes(sex, as.numeric(bipedal_percent))) +
  geom_boxplot() + 
  labs(title = "Boxplot of Bipedal Percent (without N/As) by Sex")

#Boxplot of bipedal percent without N/A's separated by substrate type and sex
ggplot(data = lab.data_omit, aes(substrate_type, as.numeric(bipedal_percent), fill = sex)) +
  geom_boxplot() +
  labs(title = "Boxplot of Bipedal Percent (without N/As) by Substrate Type and Sex")


#Lizards are running bipedal the most on debris compared to the other substrate types.
#Based on the boxplot, lizards are treating bipedalism on sand/debris as more similar to sand than debris
#Males run bipedally more frequently than females for all substrate types
```


```{r}
#Percent bipedal vs. substrate types and sex linear models
summary(lm(as.numeric(bipedal_percent) ~ substrate_type*sex, data = lab.data_omit))
anova((lm(as.numeric(bipedal_percent) ~ substrate_type*sex, data = lab.data_omit)))

#Neither substrate type nor sex is significantly effecting bipedalism according to the models
```

```{r}
#Mixed model bipedal percent and substrate type
lmer(bipedal_percent ~ substrate_type + (1 | ID), data = lab.data_omit)
summary(lmer(bipedal_percent ~ substrate_type + (1 | ID), data = lab.data_omit))

#sand and sand/debris have significant p-values
```

```{r}
#Mixed model bipedal percent and sex
lmer(bipedal_percent ~ sex + (1 | ID), data = lab.data_omit)
summary(lmer(bipedal_percent ~ sex + (1 | ID), data = lab.data_omit))
```


```{r}
#Mixed model bipedal percent and substrate type + sex
lmer(bipedal_percent ~ sex*substrate_type + (1 | ID), data = lab.data_omit)
summary(lmer(bipedal_percent ~ sex*substrate_type + (1 | ID), data = lab.data_omit))

#no interaction effects are significant
```







