---
title: 'Question 3: Is the pattern observed in question #1 explained by question #2?'
author: "Kayla Pehl"
date: "10/16/2020"
output: html_document
---

Question 3: Is the pattern observed in question #1 explained by question #2?
 Ho: Racerunners run the same on all substrates.
 Ha: Racerunners avoid moving on suboptimal parts of habitat.
 
> Data used to answer this question:
    > lab experiment data
        > velocity vs. substrate type - lmer
        > acceleration vs. substrate type - lmer 
        > bipedalism vs. substrate type - lmer
        > bipedalism vs velocity - lmer
        > power vs. substrate type ? - lmer
        > time vs. substrate type ? - lmer
    > transect data
        > effect of available cover; where is cover most frequent (more cover = safer)
    > McElroy habitat data    
        > speed vs. ground clutter crossed -- are speeds faster when more/less ground clutter is crossed?
           > lmer(speed ~ ground_clutter_crossed + (1 | ID))
        > bipedalism's effect on speed 
           > create new data set that only includes runs where bipedalism did or didn't occur
           > lmer(speed ~ bipedal + (1 | ID)
        > video analysis
           

> Would've been really helpful to have had choice experiment data for this question, but since I don't have it, it may be a lot harder to answer this question. 